// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePerformerInput struct {
	Name           string   `json:"name"`
	Disambiguation *string  `json:"disambiguation,omitempty"`
	Aliases        []string `json:"aliases,omitempty"`
}

type CreatePlatformAccountInput struct {
	PlatformID     string   `json:"platformId"`
	PlatformUserID *string  `json:"platformUserId,omitempty"`
	Handle         string   `json:"handle"`
	Bio            *string  `json:"bio,omitempty"`
	StudioID       *string  `json:"studioId,omitempty"`
	PerformerIds   []string `json:"performerIds,omitempty"`
}

type CreatePlatformInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateStudioInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateTagInput struct {
	Name         string   `json:"name"`
	Description  *string  `json:"description,omitempty"`
	PerformerIds []string `json:"performerIds,omitempty"`
}

type DeletePerformerInput struct {
	ID string `json:"id"`
}

type DeletePlatformAccountInput struct {
	ID string `json:"id"`
}

type DeleteTagInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type UpdatePerformerInput struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Disambiguation *string  `json:"disambiguation,omitempty"`
	Aliases        []string `json:"aliases,omitempty"`
}

type UpdatePlatformAccountInput struct {
	ID             string   `json:"id"`
	PlatformID     string   `json:"platformId"`
	PlatformUserID *string  `json:"platformUserId,omitempty"`
	Handle         string   `json:"handle"`
	Bio            *string  `json:"bio,omitempty"`
	StudioID       *string  `json:"studioId,omitempty"`
	PerformerIds   []string `json:"performerIds,omitempty"`
}

type UpdatePlatformInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateStudioInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateTagInput struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Description  *string  `json:"description,omitempty"`
	PerformerIds []string `json:"performerIds,omitempty"`
}

type Version struct {
	Version string `json:"version"`
}
