// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePerformerInput struct {
	Name           string   `json:"name"`
	Disambiguation *string  `json:"disambiguation,omitempty"`
	Aliases        []string `json:"aliases,omitempty"`
}

type CreatePlatformInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateStudioInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type DeletePerformerInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type UpdatePerformerInput struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Disambiguation *string  `json:"disambiguation,omitempty"`
	Aliases        []string `json:"aliases,omitempty"`
}

type UpdatePlatformInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateStudioInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Version struct {
	Version string `json:"version"`
}
