package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/load-bearing-code/stasher/api/internal/gql/model"
)

// ServerMetadata is the resolver for the serverMetadata field.
func (r *queryResolver) ServerMetadata(ctx context.Context) (*model.ServerMetadata, error) {
	tagCount, err := r.Services.Tags.Count(ctx, nil)
	if err != nil {
		return nil, err
	}
	performerCount, err := r.Services.Performers.Count(ctx)
	if err != nil {
		return nil, err
	}
	return &model.ServerMetadata{
		Version:    Version,
		Endpoint:   r.PublicURL,
		ItemCounts: &model.ServerMetadataItemCounts{Tags: tagCount, Performers: performerCount},
	}, nil
}
