package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/load-bearing-code/stasher/api/internal/gql/model"
	"github.com/load-bearing-code/stasher/api/internal/page"
	"github.com/load-bearing-code/stasher/api/internal/performers"
)

// CreatePerformer is the resolver for the createPerformer field.
func (r *mutationResolver) CreatePerformer(ctx context.Context, input model.CreatePerformerInput) (*performers.Performer, error) {
	return r.Services.Performers.Create(ctx, input.Name, input.Disambiguation, input.Aliases)
}

// UpdatePerformer is the resolver for the updatePerformer field.
func (r *mutationResolver) UpdatePerformer(ctx context.Context, input model.UpdatePerformerInput) (*performers.Performer, error) {
	return r.Services.Performers.Update(ctx, string(input.ID), input.Name, input.Disambiguation, input.Aliases)
}

// DeletePerformer is the resolver for the deletePerformer field.
func (r *mutationResolver) DeletePerformer(ctx context.Context, input model.DeletePerformerInput) (bool, error) {
	return r.Services.Performers.Delete(ctx, string(input.ID))
}

// Performers is the resolver for the performers field.
func (r *queryResolver) Performers(ctx context.Context, first *int, after *string) (*page.Connection[*performers.Performer], error) {
	args, err := page.ParseArgs(first, after)
	if err != nil {
		return nil, err
	}
	res, err := r.Services.Performers.List(ctx, args)
	if err != nil {
		return nil, err
	}
	return page.NewConnection(res, args.After != nil, (*performers.Performer).Cursor, r.Services.Performers.Count), nil
}

// Performer is the resolver for the performer field.
func (r *queryResolver) Performer(ctx context.Context, id *string, name *string) (*performers.Performer, error) {
	if (id == nil) == (name == nil) {
		return nil, errors.New("performer: specify exactly one of id or name")
	}
	return r.Services.Performers.Get(ctx, id, name)
}
