package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/load-bearing-code/stasher/api/internal/page"
	"github.com/load-bearing-code/stasher/api/internal/platforms"
)

// Platforms is the resolver for the platforms field.
func (r *queryResolver) Platforms(ctx context.Context, first *int, after *string) (*page.Connection[*platforms.Platform], error) {
	args, err := page.ParseArgs(first, after)
	if err != nil {
		return nil, err
	}
	res, err := r.Services.Platforms.List(ctx, args)
	if err != nil {
		return nil, err
	}
	return page.NewConnection(res, args.After != nil, (*platforms.Platform).Cursor, r.Services.Platforms.Count), nil
}
