package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/load-bearing-code/stasher/api/internal/gql/model"
	"github.com/load-bearing-code/stasher/api/internal/page"
	"github.com/load-bearing-code/stasher/api/internal/performers"
	"github.com/load-bearing-code/stasher/api/internal/platformaccounts"
	"github.com/load-bearing-code/stasher/api/internal/platforms"
	"github.com/load-bearing-code/stasher/api/internal/studios"
)

// CreatePlatformAccount is the resolver for the createPlatformAccount field.
func (r *mutationResolver) CreatePlatformAccount(ctx context.Context, input model.CreatePlatformAccountInput) (*platformaccounts.PlatformAccount, error) {
	return r.Services.PlatformAccounts.Create(ctx, input.PlatformID, input.PlatformUserID, input.Handle, input.Bio, input.StudioID, input.PerformerIds)
}

// UpdatePlatformAccount is the resolver for the updatePlatformAccount field.
func (r *mutationResolver) UpdatePlatformAccount(ctx context.Context, input model.UpdatePlatformAccountInput) (*platformaccounts.PlatformAccount, error) {
	return r.Services.PlatformAccounts.Update(ctx, input.ID, input.PlatformID, input.PlatformUserID, input.Handle, input.Bio, input.StudioID, input.PerformerIds)
}

// DeletePlatformAccount is the resolver for the deletePlatformAccount field.
func (r *mutationResolver) DeletePlatformAccount(ctx context.Context, input model.DeletePlatformAccountInput) (bool, error) {
	return r.Services.PlatformAccounts.Delete(ctx, input.ID)
}

// Platform is the resolver for the platform field.
func (r *platformAccountResolver) Platform(ctx context.Context, obj *platformaccounts.PlatformAccount) (*platforms.Platform, error) {
	platform, err := loadersFromContext(ctx).Platform.Load(ctx, obj.PlatformID)
	if err != nil {
		return nil, err
	}
	return &platform, nil
}

// Studio is the resolver for the studio field.
func (r *platformAccountResolver) Studio(ctx context.Context, obj *platformaccounts.PlatformAccount) (*studios.Studio, error) {
	if obj.StudioID == nil {
		return nil, nil
	}
	studio, err := loadersFromContext(ctx).Studio.Load(ctx, *obj.StudioID)
	if err != nil {
		return nil, err
	}
	return &studio, nil
}

// Performers is the resolver for the performers field.
func (r *platformAccountResolver) Performers(ctx context.Context, obj *platformaccounts.PlatformAccount) ([]*performers.Performer, error) {
	rows, err := loadersFromContext(ctx).Performer.LoadAll(ctx, obj.PerformerIDs)
	if err != nil {
		return nil, err
	}
	out := make([]*performers.Performer, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

// PlatformAccounts is the resolver for the platformAccounts field.
func (r *queryResolver) PlatformAccounts(ctx context.Context, first *int, after *string, platformID *string, performerID *string) (*page.Connection[*platformaccounts.PlatformAccount], error) {
	args, err := page.ParseArgs(first, after)
	if err != nil {
		return nil, err
	}
	res, err := r.Services.PlatformAccounts.List(ctx, args, platformID, performerID)
	if err != nil {
		return nil, err
	}
	count := func(ctx context.Context) (int, error) {
		return r.Services.PlatformAccounts.Count(ctx, platformID, performerID)
	}
	return page.NewConnection(res, args.After != nil, (*platformaccounts.PlatformAccount).Cursor, count), nil
}

// PlatformAccount is the resolver for the platformAccount field.
func (r *queryResolver) PlatformAccount(ctx context.Context, id *string, platformID *string, handle *string) (*platformaccounts.PlatformAccount, error) {
	if id != nil {
		if platformID != nil || handle != nil {
			return nil, errors.New("platformAccount: specify either id, or platformId and handle together")
		}
	} else if platformID == nil || handle == nil {
		return nil, errors.New("platformAccount: specify either id, or platformId and handle together")
	}
	return r.Services.PlatformAccounts.Get(ctx, id, platformID, handle)
}

// PlatformAccount returns PlatformAccountResolver implementation.
func (r *Resolver) PlatformAccount() PlatformAccountResolver { return &platformAccountResolver{r} }

type platformAccountResolver struct{ *Resolver }
