package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/load-bearing-code/stasher/api/internal/gql/model"
	"github.com/load-bearing-code/stasher/api/internal/page"
	"github.com/load-bearing-code/stasher/api/internal/platforms"
)

// CreatePlatform is the resolver for the createPlatform field.
func (r *mutationResolver) CreatePlatform(ctx context.Context, input model.CreatePlatformInput) (*platforms.Platform, error) {
	return r.Services.Platforms.Create(ctx, string(input.ID), input.Name)
}

// UpdatePlatform is the resolver for the updatePlatform field.
func (r *mutationResolver) UpdatePlatform(ctx context.Context, input model.UpdatePlatformInput) (*platforms.Platform, error) {
	return r.Services.Platforms.Update(ctx, string(input.ID), input.Name)
}

// Platforms is the resolver for the platforms field.
func (r *queryResolver) Platforms(ctx context.Context, first *int, after *string) (*page.Connection[*platforms.Platform], error) {
	args, err := page.ParseArgs(first, after)
	if err != nil {
		return nil, err
	}
	res, err := r.Services.Platforms.List(ctx, args)
	if err != nil {
		return nil, err
	}
	return page.NewConnection(res, args.After != nil, (*platforms.Platform).Cursor, r.Services.Platforms.Count), nil
}

// Platform is the resolver for the platform field.
func (r *queryResolver) Platform(ctx context.Context, id *string, name *string) (*platforms.Platform, error) {
	if (id == nil) == (name == nil) {
		return nil, errors.New("platform: specify exactly one of id or name")
	}
	return r.Services.Platforms.Get(ctx, id, name)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
