package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/load-bearing-code/stasher/api/internal/gql/model"
	"github.com/load-bearing-code/stasher/api/internal/page"
	"github.com/load-bearing-code/stasher/api/internal/studios"
)

// CreateStudio is the resolver for the createStudio field.
func (r *mutationResolver) CreateStudio(ctx context.Context, input model.CreateStudioInput) (*studios.Studio, error) {
	return r.Services.Studios.Create(ctx, string(input.ID), input.Name)
}

// UpdateStudio is the resolver for the updateStudio field.
func (r *mutationResolver) UpdateStudio(ctx context.Context, input model.UpdateStudioInput) (*studios.Studio, error) {
	return r.Services.Studios.Update(ctx, string(input.ID), input.Name)
}

// Studios is the resolver for the studios field.
func (r *queryResolver) Studios(ctx context.Context, first *int, after *string) (*page.Connection[*studios.Studio], error) {
	args, err := page.ParseArgs(first, after)
	if err != nil {
		return nil, err
	}
	res, err := r.Services.Studios.List(ctx, args)
	if err != nil {
		return nil, err
	}
	return page.NewConnection(res, args.After != nil, (*studios.Studio).Cursor, r.Services.Studios.Count), nil
}

// Studio is the resolver for the studio field.
func (r *queryResolver) Studio(ctx context.Context, id *string, name *string) (*studios.Studio, error) {
	if (id == nil) == (name == nil) {
		return nil, errors.New("studio: specify exactly one of id or name")
	}
	return r.Services.Studios.Get(ctx, id, name)
}
