package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/load-bearing-code/stasher/api/internal/gql/model"
	"github.com/load-bearing-code/stasher/api/internal/page"
	"github.com/load-bearing-code/stasher/api/internal/performers"
	"github.com/load-bearing-code/stasher/api/internal/tags"
)

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*tags.Tag, error) {
	return r.Services.Tags.Create(ctx, input.Name, input.Description, input.PerformerIds)
}

// UpdateTag is the resolver for the updateTag field.
func (r *mutationResolver) UpdateTag(ctx context.Context, input model.UpdateTagInput) (*tags.Tag, error) {
	return r.Services.Tags.Update(ctx, input.ID, input.Name, input.Description, input.PerformerIds)
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, input model.DeleteTagInput) (bool, error) {
	return r.Services.Tags.Delete(ctx, input.ID)
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context, first *int, after *string, performerID *string) (*page.Connection[*tags.Tag], error) {
	args, err := page.ParseArgs(first, after)
	if err != nil {
		return nil, err
	}
	res, err := r.Services.Tags.List(ctx, args, performerID)
	if err != nil {
		return nil, err
	}
	count := func(ctx context.Context) (int, error) {
		return r.Services.Tags.Count(ctx, performerID)
	}
	return page.NewConnection(res, args.After != nil, (*tags.Tag).Cursor, count), nil
}

// Tag is the resolver for the tag field.
func (r *queryResolver) Tag(ctx context.Context, id *string, name *string) (*tags.Tag, error) {
	if (id == nil) == (name == nil) {
		return nil, errors.New("tag: specify exactly one of id or name")
	}
	return r.Services.Tags.Get(ctx, id, name)
}

// Performers is the resolver for the performers field.
func (r *tagResolver) Performers(ctx context.Context, obj *tags.Tag) ([]*performers.Performer, error) {
	rows, err := loadersFromContext(ctx).Performer.LoadAll(ctx, obj.PerformerIDs)
	if err != nil {
		return nil, err
	}
	out := make([]*performers.Performer, len(rows))
	for i := range rows {
		out[i] = &rows[i]
	}
	return out, nil
}

// Tag returns TagResolver implementation.
func (r *Resolver) Tag() TagResolver { return &tagResolver{r} }

type tagResolver struct{ *Resolver }
