type Studio {
  id: ID!
  name: String!
}

type StudioEdge {
  node: Studio!
  cursor: String!
}

type StudioConnection {
  edges: [StudioEdge!]!
  pageInfo: PageInfo!
  totalCount: Int!
}

extend type Query {
  studios(first: Int, after: String): StudioConnection!
  studio(id: ID, name: String): Studio
}

input CreateStudioInput {
  id: ID!
  name: String!
}

input UpdateStudioInput {
  id: ID!
  name: String!
}

extend type Mutation {
  createStudio(input: CreateStudioInput!): Studio!
  updateStudio(input: UpdateStudioInput!): Studio!
}
